export const GET_FREQUENT_WORDS_SUCCESS = "GET_FREQUENT_WORDS_SUCCESS";
export const GET_WORDS_SUCCESS = "GET_WORDS_SUCCESS";
export const GET_WORDS_ERROR = "GET_WORDS_ERROR";
export const UPDATE_LOADING_STATUS = "UPDATE_LOADING_STATUS";